"""Load the committed per-resource wiring specs into typed Stage-2 / Stage-3 configs.

``resource_specs.json`` is the reviewed artifact (generated by ``scripts/stage3_5_gen_specs.py``).
Each entry is either a wiring spec or ``{"deferred": "<reason>"}``. This module turns the wiring
specs into the same :class:`ResourceNormalizeConfig` / :class:`ResourceResolveConfig` the pipelines
already consume, and exposes the deferrals verbatim (preserved + flagged, never dropped).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from data_platform.normalize.config import ColumnType, ResourceNormalizeConfig
from data_platform.normalize.reshape import ReshapeSpec
from data_platform.resolve.config import GeoColumns, ResourceResolveConfig
from data_platform.resolve.models import GeoLevel

_SPECS_PATH = Path(__file__).parent / "resource_specs.json"


@dataclass(frozen=True)
class WiredResource:
    """Everything the driver needs to carry one resource to a resolved state."""

    resource_id: str
    source_id: str
    source_grain: str
    file: str
    normalize_config: ResourceNormalizeConfig
    resolve_config: ResourceResolveConfig


def _normalize_config(spec: dict[str, Any]) -> ResourceNormalizeConfig:
    return ResourceNormalizeConfig(
        reshape=ReshapeSpec(**spec["reshape"]),
        column_types={col: ColumnType(kind) for col, kind in spec["column_types"].items()},
        grain_key_columns=list(spec["grain_key_columns"]),
    )


def _resolve_config(spec: dict[str, Any]) -> ResourceResolveConfig:
    geo = spec.get("geo_columns")
    return ResourceResolveConfig(
        geo_level=GeoLevel(spec["geo_level"]),
        scheme_label=spec["scheme_label"],
        geo_columns=GeoColumns(**geo) if geo is not None else None,
    )


def _load() -> tuple[dict[str, WiredResource], dict[str, str]]:
    raw: dict[str, Any] = json.loads(_SPECS_PATH.read_text())
    wired: dict[str, WiredResource] = {}
    deferred: dict[str, str] = {}
    for resource_id, spec in raw.items():
        if "deferred" in spec:
            deferred[resource_id] = spec["deferred"]
            continue
        wired[resource_id] = WiredResource(
            resource_id=resource_id,
            source_id=spec["source_id"],
            source_grain=spec["source_grain"],
            file=spec["file"],
            normalize_config=_normalize_config(spec),
            resolve_config=_resolve_config(spec),
        )
    return wired, deferred


_wired, _deferred = _load()
WIRED: Final[dict[str, WiredResource]] = _wired
DEFERRED: Final[dict[str, str]] = _deferred
