"""Stage 3 integration over the REAL local archive — skips when the archive is absent.

``data/`` is gitignored (regenerated by fetch scripts), so this test is a no-op on a fresh
checkout and CI; it runs locally where the archive exists, validating the curated alias tables
and the resolver against live LGD + flagship data. Two guarantees:

1. **Alias integrity** — every STATE/DISTRICT alias target actually exists in the real LGD
   reference (a typo'd target would silently quarantine instead of resolve).
2. **Resolution coverage** — over every DISTINCT flagship (state, district), the set that fails
   to resolve is EXACTLY the known, reviewed quarantine set (new districts absent from this LGD
   snapshot + non-district administrative bodies + the null-junk state). Any drift — a newly
   broken alias or an unexpected unresolved name — fails loudly.

Resolution is checked at the distinct-geography grain (not all ~416k rows): entity resolution is
a property of the geography universe, and distinct pairs are the meaningful coverage unit.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from data_platform.resolve.aliases import DISTRICT_ALIASES, STATE_ALIASES
from data_platform.resolve.geo import GeoResolver
from data_platform.resolve.lgd import load_lgd_reference

_ROOT = Path(__file__).resolve().parents[2]
_ARCHIVE = _ROOT / "data" / "archive"
_FLAGSHIP = _ARCHIVE / "ee03643a-ee4c-48c2-ac30-9f2ff26ab722.json"
_LGD_STATES = _ARCHIVE / "lgd" / "lgd_states.json"
_LGD_DISTRICTS = _ARCHIVE / "lgd" / "lgd_districts.json"

pytestmark = pytest.mark.skipif(
    not (_FLAGSHIP.exists() and _LGD_STATES.exists() and _LGD_DISTRICTS.exists()),
    reason="local archive (gitignored) not present — integration test is offline/local-only",
)

# The reviewed quarantine set (R3-GEO-05), by verbatim flagship (state, district) — names the
# resolver must NOT resolve: new districts absent from this LGD snapshot, and non-district bodies.
_EXPECTED_DISTRICT_QUARANTINE = {
    ("ANDHRA PRADESH", "Markapuram"),
    ("ANDHRA PRADESH", "Polavaram"),
    ("ARUNACHAL PRADESH", "KEYI PANYOR"),
    ("KARNATAKA", "BENGALURU SOUTH"),
    ("WEST BENGAL", "Darjeeling Gorkha Hill Council (DGHC)"),
    ("WEST BENGAL", "GORKHALAND TERRITORIAL ADMINISTRATION (GTA)"),
    ("WEST BENGAL", "Gorkhaland Territorial Administration (GTA)"),
    ("WEST BENGAL", "SILIGURI MAHAKUMA PARISAD"),
}
_EXPECTED_STATE_QUARANTINE = {"NA"}  # null-junk state (Stage-2 nulls it; junk token here too)


def _resolver() -> GeoResolver:
    states, districts = load_lgd_reference(_LGD_STATES, _LGD_DISTRICTS)
    return GeoResolver.from_reference(states=states, districts=districts)


def _distinct_pairs() -> set[tuple[str, str]]:
    records = json.loads(_FLAGSHIP.read_text())["records"]
    return {(r["state_name"], r["district_name"]) for r in records}


def test_every_state_alias_target_exists_in_lgd() -> None:
    resolver = _resolver()
    for target in STATE_ALIASES.values():
        assert resolver.resolve_state(target) is not None, f"broken state alias target: {target!r}"


def test_every_district_alias_target_exists_in_lgd() -> None:
    resolver = _resolver()
    for (state_code, _src), target in DISTRICT_ALIASES.items():
        match = resolver.resolve_district(state_code, target)
        assert match is not None, f"broken district alias target: {state_code} -> {target!r}"


def test_resolution_coverage_matches_reviewed_quarantine_set() -> None:
    resolver = _resolver()
    pairs = _distinct_pairs()

    state_unresolved: set[str] = set()
    district_unresolved: set[tuple[str, str]] = set()
    resolved = 0
    for state_name, district_name in pairs:
        state = resolver.resolve_state(state_name)
        if state is None:
            state_unresolved.add(state_name)
            continue
        if resolver.resolve_district(state.code, district_name) is None:
            district_unresolved.add((state_name, district_name.strip()))
        else:
            resolved += 1

    expected_quarantine = {(s, d.strip()) for s, d in _EXPECTED_DISTRICT_QUARANTINE}
    assert state_unresolved == _EXPECTED_STATE_QUARANTINE
    assert district_unresolved == expected_quarantine
    # Sanity on scale: the vast majority of the geography universe resolves.
    assert resolved == len(pairs) - len(district_unresolved) - sum(
        1 for s, _ in pairs if s in state_unresolved
    )
    assert resolved / len(pairs) > 0.98
